version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            npm install
            npm run eslint
            npm run format:check
            npm run build
            npm test
  release:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Build and Release
          command: |
            npm install
            next_version=$(npx semantic-release --branch ${CIRCLE_BRANCH} --dry-run | grep "The next release version is" | sed -n -e 's/^.*is //p')
            sed -i "s/version.*/version: \"${next_version}\"/g" plugin.yaml
            npm run build
            npx semantic-release --branch ${CIRCLE_BRANCH}
workflows:
  version: 2
  build_test_release:
    jobs:
      - build_and_test
      - release:
          context: nodejs-lib-release
          requires:
            - build_and_test
          filters:
            branches:
              only: master
