version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            npm install
            npm run eslint
            npm run format:check
            npm run build
            npm test

  version_check:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Version Check for Semantic Release
          command: |
            npm install  # required here for semantic-release install
            next_version=$(npx semantic-release --branch ${CIRCLE_BRANCH} --dry-run | grep "The next release version is" | sed -n -e 's/^.*is //p')
            sed -i "s/version.*/version: \"${next_version}\"/g" plugin.yaml
            npx semantic-release --branch ${CIRCLE_BRANCH}
  release:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run:
          name: Create binaries with pkg
          command: |
            npm run pkg
            shasum -a 256 helm-snyk-linux > helm-snyk-linux.sha256
            shasum -a 256 helm-snyk-macos > helm-snyk-macos.sha256
            shasum -a 256 helm-snyk-win.exe > helm-snyk-win.exe.sha256
            ls -la
      - run:
          name: Semantic Release
          command: |
            echo "doing semantic-release..."
            npx semantic-release

workflows:
  version: 2
  build_test_release:
    jobs:
      - build_and_test
      - version_check:
          context: nodejs-lib-release
          filters:
            branches:
              only: master
      - release:
          context: nodejs-lib-release
          requires:
            - version_check
            - build_and_test
          filters:
            branches:
              only: master
